name: CI

on:
  pull_request:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'
  push:
    paths-ignore:
      - 'build/**'
      - 'docs/**'
      - 'files/**'

jobs:

  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 使用 Nnode.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: Build packages
        run: pnpm run build
      - name: === Linting ===
        run: pnpm run lint

  unit:
    name: "Unit testing"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 使用 Nnode.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: Install packages
        run: |
          pnpm install
          pnpm install --prefix test
      - name: Build
        run: pnpm run build
      - name: === Unit testing ===
        run: pnpm run test-unit

  e2e:
    name: "E2E testing"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CI: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
    env:
      CI: ${{ matrix.CI }}
      FORCE_COLOR: 1
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 使用 Nnode.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install packages
        run: |
          pnpm install
          pnpm install --prefix test
          sudo apt-get install -y xvfb
      - name: Build
        run: pnpm run build
      - name: === E2E testing ===
        run: xvfb-run --auto-servernum pnpm run test-e2e

  e2e-cov:
    name: "Ready for release"
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: 安装 pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: 使用 Nnode.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: === Ready for release ===
        run: pnpm run test-e2e-cov
